"""update game table

Revision ID: 6fe0aa3d384d
Revises: 178d39a4a463
Create Date: 2018-12-14 17:37:01.826521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe0aa3d384d'
down_revision = '178d39a4a463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
