"""game_numbers_set

Revision ID: cb3f36770a38
Revises: d68f33013a6a
Create Date: 2018-12-20 19:30:21.957833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3f36770a38'
down_revision = 'd68f33013a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
