"""game_numbers_set

Revision ID: 643e70db5fb5
Revises: 7fe5ce670cfc
Create Date: 2018-12-20 19:42:57.883594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643e70db5fb5'
down_revision = '7fe5ce670cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
