"""update ForeignGatherRecordModel

Revision ID: 38cc90c6dda9
Revises: fa08dac04b4a
Create Date: 2018-12-17 18:28:51.281109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cc90c6dda9'
down_revision = 'fa08dac04b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foreign_gather_record', sa.Column('process_record', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foreign_gather_record', 'process_record')
    # ### end Alembic commands ###
