"""robot_config_record

Revision ID: fa08dac04b4a
Revises: 197bfdfcfa93
Create Date: 2018-12-17 15:03:51.381824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa08dac04b4a'
down_revision = '197bfdfcfa93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
