"""update TokenConfModel

Revision ID: 178d39a4a463
Revises: f6ca1e97d6d5
Create Date: 2018-12-14 14:42:55.498084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178d39a4a463'
down_revision = 'f6ca1e97d6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_conf', sa.Column('gather_gas', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False))
    op.add_column('token_conf', sa.Column('gather_minimum_amount', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_conf', 'gather_minimum_amount')
    op.drop_column('token_conf', 'gather_gas')
    # ### end Alembic commands ###
