"""game_numbers_set

Revision ID: 7fe5ce670cfc
Revises: cb3f36770a38
Create Date: 2018-12-20 19:35:04.481929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe5ce670cfc'
down_revision = 'cb3f36770a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
