"""modify winning_record

Revision ID: 90ca5f86ad5c
Revises: 037012968521
Create Date: 2018-12-24 19:40:28.583605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ca5f86ad5c'
down_revision = '037012968521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winning_record', sa.Column('merge_id', sa.BigInteger(), server_default='-1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('winning_record', 'merge_id')
    # ### end Alembic commands ###
