"""game_numbers_set

Revision ID: 302e81bb64b5
Revises: 0af3d7d64493
Create Date: 2018-12-20 19:24:00.808124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '302e81bb64b5'
down_revision = '0af3d7d64493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
