"""game_numbers_set

Revision ID: d68f33013a6a
Revises: 302e81bb64b5
Create Date: 2018-12-20 19:28:08.111763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68f33013a6a'
down_revision = '302e81bb64b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
