"""use account add inviter code and invitee code

Revision ID: d71fbd22a3a4
Revises: 90ca5f86ad5c
Create Date: 2018-12-26 10:27:09.815885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd71fbd22a3a4'
down_revision = '90ca5f86ad5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('invitee_code', mysql.CHAR(length=8), nullable=False))
    op.add_column('user_account', sa.Column('inviter_code', mysql.CHAR(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'inviter_code')
    op.drop_column('user_account', 'invitee_code')
    # ### end Alembic commands ###
