"""change the default time about game table

Revision ID: a1ca23865008
Revises: 35fea5c935e8
Create Date: 2018-12-16 13:31:57.682306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ca23865008'
down_revision = '35fea5c935e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
