"""update game_digital_instance

Revision ID: 35fea5c935e8
Revises: 6fe0aa3d384d
Create Date: 2018-12-16 12:46:20.155801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35fea5c935e8'
down_revision = '6fe0aa3d384d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_digital_instance', sa.Column('chain_status', mysql.INTEGER(), server_default='0', nullable=False))
    op.add_column('game_digital_instance', sa.Column('support_token', mysql.INTEGER(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_digital_instance', 'support_token')
    op.drop_column('game_digital_instance', 'chain_status')
    # ### end Alembic commands ###
