"""game_numbers_set

Revision ID: 0af3d7d64493
Revises: 0bf567adbb9c
Create Date: 2018-12-20 19:15:31.295137

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0af3d7d64493'
down_revision = '0bf567adbb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_numbers_set',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('game_serial', sa.String(length=64), server_default='', nullable=False),
    sa.Column('number', sa.BigInteger(), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_numbers_set')
    # ### end Alembic commands ###
