"""update sync_eos delete column

Revision ID: 97b29dd19a2b
Revises: 5730b1cf032d
Create Date: 2019-01-14 15:46:48.043970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97b29dd19a2b'
down_revision = '5730b1cf032d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_eos', 'ref_block_prefix')
    op.drop_column('sync_eos', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_eos', sa.Column('confirmed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('sync_eos', sa.Column('ref_block_prefix', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
