"""update SyncBlockModel1

Revision ID: 389c011f2e53
Revises: 19ac37e57294
Create Date: 2019-01-02 16:08:32.957829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389c011f2e53'
down_revision = '19ac37e57294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('coin_id', table_name='sync_block')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('coin_id', 'sync_block', ['coin_id'], unique=True)
    # ### end Alembic commands ###
