"""update token_node_conf

Revision ID: 58e80cd668e2
Revises: aef410f2e570
Create Date: 2019-01-18 12:51:57.646628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e80cd668e2'
down_revision = 'aef410f2e570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_node_conf', sa.Column('script_unit', sa.String(length=16), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_node_conf', 'script_unit')
    # ### end Alembic commands ###
