"""create game_get_lottery_block_info_eos

Revision ID: b4dcd91a18ad
Revises: 97b29dd19a2b
Create Date: 2019-01-14 19:53:44.967576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4dcd91a18ad'
down_revision = '97b29dd19a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_get_lottery_block_info_eos',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('game_instance_id', sa.BigInteger(), nullable=False),
    sa.Column('base_block_num', sa.INTEGER(), nullable=True),
    sa.Column('base_time_stamp', sa.Numeric(precision=21, scale=3), nullable=True),
    sa.Column('block_num', sa.INTEGER(), nullable=True),
    sa.Column('block_hash', sa.String(length=64), server_default='', nullable=False),
    sa.Column('time_stamp', sa.String(length=255), server_default='0000-00-00T00:00:00.000', nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('base_block_num'),
    sa.UniqueConstraint('base_time_stamp')
    )
    op.create_index(op.f('ix_game_get_lottery_block_info_eos_block_hash'), 'game_get_lottery_block_info_eos', ['block_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_get_lottery_block_info_eos_block_hash'), table_name='game_get_lottery_block_info_eos')
    op.drop_table('game_get_lottery_block_info_eos')
    # ### end Alembic commands ###
