"""update sync_eos block_num set unique

Revision ID: 8d49c3e34d29
Revises: 2a0c0010e862
Create Date: 2019-01-11 15:50:19.591978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d49c3e34d29'
down_revision = '2a0c0010e862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sync_eos', ['block_num'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_eos', type_='unique')
    # ### end Alembic commands ###
