"""update sync_eos add time_stamp_decimal

Revision ID: 2316784340d5
Revises: 8d49c3e34d29
Create Date: 2019-01-11 17:41:48.272087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2316784340d5'
down_revision = '8d49c3e34d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_eos', sa.Column('time_stamp_decimal', sa.Numeric(precision=21, scale=3), nullable=True))
    op.drop_index('time_stamp_int', table_name='sync_eos')
    op.create_unique_constraint(None, 'sync_eos', ['time_stamp_decimal'])
    op.drop_column('sync_eos', 'time_stamp_int')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_eos', sa.Column('time_stamp_int', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sync_eos', type_='unique')
    op.create_index('time_stamp_int', 'sync_eos', ['time_stamp_int'], unique=True)
    op.drop_column('sync_eos', 'time_stamp_decimal')
    # ### end Alembic commands ###
