"""update tx_listening_eos add memo

Revision ID: 67dc9bc168c6
Revises: b1120c4e714d
Create Date: 2019-01-23 14:14:44.299748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dc9bc168c6'
down_revision = 'b1120c4e714d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tx_listening_eos', sa.Column('memo', sa.String(length=512), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tx_listening_eos', 'memo')
    # ### end Alembic commands ###
