"""add profile picture

Revision ID: 9518e555b0d5
Revises: 52002ea237a1
Create Date: 2019-01-07 18:53:07.784302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9518e555b0d5'
down_revision = '52002ea237a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('profile_picture', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'profile_picture')
    # ### end Alembic commands ###
