"""model add memo

Revision ID: 34eb42070a6c
Revises: 04e1b9d2bec8
Create Date: 2019-01-17 12:28:59.951474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34eb42070a6c'
down_revision = '04e1b9d2bec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_change_record', sa.Column('memo', sa.String(length=512), server_default='', nullable=False))
    op.add_column('account_recharge_record', sa.Column('memo', sa.String(length=512), server_default='', nullable=False))
    op.add_column('account_withdraw_record', sa.Column('memo', sa.String(length=512), server_default='', nullable=False))
    op.add_column('user_account_token', sa.Column('memo', sa.String(length=512), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account_token', 'memo')
    op.drop_column('account_withdraw_record', 'memo')
    op.drop_column('account_recharge_record', 'memo')
    op.drop_column('account_change_record', 'memo')
    # ### end Alembic commands ###
