"""operational activities model

Revision ID: 15cfd3f5e37d
Revises: 80b7cb4ef9a2
Create Date: 2019-02-21 10:38:11.494390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15cfd3f5e37d'
down_revision = '80b7cb4ef9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_activities',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('user_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('operational_activities_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('operational_activities_name', sa.String(length=128), server_default='', nullable=False),
    sa.Column('labels', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operational_activities')
    # ### end Alembic commands ###
