"""update foreign_withdraw_order_record add memo 

Revision ID: f7df5857ea53
Revises: 6ebd00e01c43
Create Date: 2019-01-18 18:16:09.151094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7df5857ea53'
down_revision = '6ebd00e01c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foreign_withdraw_order_record', sa.Column('memo', sa.String(length=512), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foreign_withdraw_order_record', 'memo')
    # ### end Alembic commands ###
