"""update sync_eos add time_stamp_int

Revision ID: 2a0c0010e862
Revises: 62ff9ffe0d9d
Create Date: 2019-01-11 15:40:48.595118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0c0010e862'
down_revision = '62ff9ffe0d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_eos', sa.Column('time_stamp_int', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'sync_eos', ['time_stamp_int'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_eos', type_='unique')
    op.drop_column('sync_eos', 'time_stamp_int')
    # ### end Alembic commands ###
