"""add first_lottery

Revision ID: c27157d9343c
Revises: 389c011f2e53
Create Date: 2019-01-03 13:40:01.383720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c27157d9343c'
down_revision = '389c011f2e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('first_lottery', mysql.TINYINT(display_width=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'first_lottery')
    # ### end Alembic commands ###
