"""test nick_name data

Revision ID: f23f6c02f755
Revises: fb2cf456423b
Create Date: 2019-01-04 11:20:01.474397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f23f6c02f755'
down_revision = 'fb2cf456423b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nick_name_list', sa.Column('birthday', sa.String(length=200), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('contact_info', sa.String(length=300), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('description', sa.String(length=500), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('education_info', sa.String(length=300), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('fans_num', mysql.INTEGER(), server_default='0', nullable=False))
    op.add_column('nick_name_list', sa.Column('follows_num', mysql.INTEGER(), server_default='0', nullable=False))
    op.add_column('nick_name_list', sa.Column('gender', mysql.INTEGER(), server_default='0', nullable=False))
    op.add_column('nick_name_list', sa.Column('head_img', sa.String(length=500), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('level', mysql.INTEGER(), server_default='0', nullable=False))
    op.add_column('nick_name_list', sa.Column('location', sa.String(length=100), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('name', sa.String(length=200), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('register_time', sa.String(length=200), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('tags', sa.String(length=500), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('uid', sa.String(length=20), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('verify_info', sa.String(length=2500), server_default='', nullable=False))
    op.add_column('nick_name_list', sa.Column('verify_type', mysql.INTEGER(), server_default='0', nullable=False))
    op.add_column('nick_name_list', sa.Column('wb_num', mysql.INTEGER(), server_default='0', nullable=False))
    op.add_column('nick_name_list', sa.Column('work_info', sa.String(length=500), server_default='', nullable=False))
    op.drop_index('user_id', table_name='nick_name_list')
    op.create_unique_constraint(None, 'nick_name_list', ['uid'])
    op.drop_column('nick_name_list', 'user_id')
    op.drop_column('nick_name_list', 'nick_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nick_name_list', sa.Column('nick_name', mysql.VARCHAR(collation='utf8mb4_bin', length=64), server_default=sa.text("''"), nullable=False))
    op.add_column('nick_name_list', sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_bin', length=64), server_default=sa.text("''"), nullable=False))
    op.drop_constraint(None, 'nick_name_list', type_='unique')
    op.create_index('user_id', 'nick_name_list', ['user_id'], unique=True)
    op.drop_column('nick_name_list', 'work_info')
    op.drop_column('nick_name_list', 'wb_num')
    op.drop_column('nick_name_list', 'verify_type')
    op.drop_column('nick_name_list', 'verify_info')
    op.drop_column('nick_name_list', 'uid')
    op.drop_column('nick_name_list', 'tags')
    op.drop_column('nick_name_list', 'register_time')
    op.drop_column('nick_name_list', 'name')
    op.drop_column('nick_name_list', 'location')
    op.drop_column('nick_name_list', 'level')
    op.drop_column('nick_name_list', 'head_img')
    op.drop_column('nick_name_list', 'gender')
    op.drop_column('nick_name_list', 'follows_num')
    op.drop_column('nick_name_list', 'fans_num')
    op.drop_column('nick_name_list', 'education_info')
    op.drop_column('nick_name_list', 'description')
    op.drop_column('nick_name_list', 'contact_info')
    op.drop_column('nick_name_list', 'birthday')
    # ### end Alembic commands ###
