"""update SyncBlockModel

Revision ID: 19ac37e57294
Revises: 1efd349a6630
Create Date: 2019-01-02 16:01:50.221489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ac37e57294'
down_revision = '1efd349a6630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_block', sa.Column('process', sa.String(length=8), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_block', 'process')
    # ### end Alembic commands ###
