"""add app_upgrade table

Revision ID: 5730b1cf032d
Revises: 2316784340d5
Create Date: 2019-01-14 13:58:09.008238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5730b1cf032d'
down_revision = '2316784340d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_upgrade',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('version_code', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('version_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('upgrade_describe', sa.String(length=255), server_default='', nullable=False),
    sa.Column('download_link', sa.String(length=255), server_default='', nullable=False),
    sa.Column('forced_update', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('status', mysql.TINYINT(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('version_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_upgrade')
    # ### end Alembic commands ###
