"""add block_hash col

Revision ID: aef410f2e570
Revises: 34eb42070a6c
Create Date: 2019-01-17 14:20:57.580950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef410f2e570'
down_revision = '34eb42070a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dice_participate_in', sa.Column('block_hash', sa.String(length=64), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dice_participate_in', 'block_hash')
    # ### end Alembic commands ###
