"""create tx_list_eos

Revision ID: a540fdd257f5
Revises: f7df5857ea53
Create Date: 2019-01-18 19:04:53.632478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a540fdd257f5'
down_revision = 'f7df5857ea53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tx_list_eos',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tx_id', sa.String(length=32), server_default='', nullable=False),
    sa.Column('tx_no', sa.String(length=128), server_default='', nullable=False),
    sa.Column('vout', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('block_no', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.Numeric(precision=21, scale=18), nullable=False),
    sa.Column('address', sa.String(length=255), server_default='', nullable=False),
    sa.Column('cost_flag', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('source_status', sa.String(length=8), server_default='0', nullable=False),
    sa.Column('do_recharge_result', sa.String(length=255), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('tx_no')
    )
    op.create_table('tx_listening_eos',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('order_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('record_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('block_no', sa.INTEGER(), nullable=False),
    sa.Column('tx_no', sa.String(length=128), server_default='', nullable=False),
    sa.Column('tx_nos', mysql.TEXT(), nullable=True),
    sa.Column('withdraw_type', sa.String(length=8), server_default='', nullable=False),
    sa.Column('listen_flag', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('source_status', sa.String(length=8), server_default='0', nullable=False),
    sa.Column('multi_flag', mysql.TINYINT(display_width=4), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('order_no'),
    sa.UniqueConstraint('tx_no')
    )
    op.add_column('tx_list_eth', sa.Column('symbol', sa.String(length=32), server_default='EOS', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tx_list_eth', 'symbol')
    op.drop_table('tx_listening_eos')
    op.drop_table('tx_list_eos')
    # ### end Alembic commands ###
