"""update sync_block add 

Revision ID: 0d990b2e222c
Revises: 58e80cd668e2
Create Date: 2019-01-18 15:20:43.787131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d990b2e222c'
down_revision = '58e80cd668e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_block', sa.Column('trace_count', sa.String(length=255), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_block', 'trace_count')
    # ### end Alembic commands ###
