"""add nick_name_list

Revision ID: fb2cf456423b
Revises: c27157d9343c
Create Date: 2019-01-04 11:05:35.978757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2cf456423b'
down_revision = 'c27157d9343c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nick_name_list',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('nick_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('user_id', sa.String(length=64), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nick_name_list')
    # ### end Alembic commands ###
