"""create sync_eos

Revision ID: 62ff9ffe0d9d
Revises: 3e9e41927fef
Create Date: 2019-01-11 15:17:36.630272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62ff9ffe0d9d'
down_revision = '3e9e41927fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_eos',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('block_num', sa.INTEGER(), nullable=False),
    sa.Column('block_hash', sa.String(length=255), server_default='', nullable=False),
    sa.Column('time_stamp', sa.String(length=255), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('confirmed', sa.INTEGER(), nullable=False),
    sa.Column('ref_block_prefix', sa.INTEGER(), nullable=False),
    sa.Column('previous', sa.String(length=255), server_default='', nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('process', sa.String(length=8), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_eos')
    # ### end Alembic commands ###
