"""add col bet_hash

Revision ID: 80b7cb4ef9a2
Revises: 04b834f88069
Create Date: 2019-02-16 14:59:24.697650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80b7cb4ef9a2'
down_revision = '04b834f88069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participate_in', sa.Column('bet_hash', sa.String(length=255), server_default='', nullable=False))
    op.add_column('participate_in', sa.Column('block_no', mysql.INTEGER(), server_default='0', nullable=False))
    op.add_column('participate_in', sa.Column('received_time', sa.String(length=128), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participate_in', 'received_time')
    op.drop_column('participate_in', 'block_no')
    op.drop_column('participate_in', 'bet_hash')
    # ### end Alembic commands ###
