"""alter user

Revision ID: 089c3fe7c99c
Revises: e0d8caf7f33f
Create Date: 2018-11-09 09:54:51.478730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089c3fe7c99c'
down_revision = 'e0d8caf7f33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invest_users', sa.Column('real_name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'invest_users', ['real_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invest_users', type_='unique')
    op.drop_column('invest_users', 'real_name')
    # ### end Alembic commands ###
