"""alter users

Revision ID: 222bf40769c8
Revises: 964a7090b563
Create Date: 2018-09-13 08:48:31.705503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222bf40769c8'
down_revision = '964a7090b563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_users', sa.Column('id_card', sa.String(length=64), server_default='', nullable=False))
    op.add_column('borrow_users', sa.Column('real_name', sa.String(length=64), server_default='', nullable=False))
    op.create_unique_constraint(None, 'borrow_users', ['id_card'])
    op.create_unique_constraint(None, 'borrow_users', ['real_name'])
    op.add_column('invest_users', sa.Column('id_card', sa.String(length=64), server_default='', nullable=False))
    op.add_column('invest_users', sa.Column('real_name', sa.String(length=64), server_default='', nullable=False))
    op.create_unique_constraint(None, 'invest_users', ['real_name'])
    op.create_unique_constraint(None, 'invest_users', ['id_card'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invest_users', type_='unique')
    op.drop_constraint(None, 'invest_users', type_='unique')
    op.drop_column('invest_users', 'real_name')
    op.drop_column('invest_users', 'id_card')
    op.drop_constraint(None, 'borrow_users', type_='unique')
    op.drop_constraint(None, 'borrow_users', type_='unique')
    op.drop_column('borrow_users', 'real_name')
    op.drop_column('borrow_users', 'id_card')
    # ### end Alembic commands ###
