"""alter keysaltmodel

Revision ID: 28c1d1023ee7
Revises: ca8f4e92d51b
Create Date: 2018-09-03 12:56:18.591308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c1d1023ee7'
down_revision = 'ca8f4e92d51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
