"""alter adminuser

Revision ID: 336e416e75d1
Revises: bc1cf5e73385
Create Date: 2018-10-19 16:46:09.000661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336e416e75d1'
down_revision = 'bc1cf5e73385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin_users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='unique')
    # ### end Alembic commands ###
