"""alter tables

Revision ID: 7151cc434cb4
Revises: 336e416e75d1
Create Date: 2018-10-31 08:23:23.781514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7151cc434cb4'
down_revision = '336e416e75d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invest_users', sa.Column('email', sa.String(length=128), server_default='', nullable=False))
    op.add_column('invest_users', sa.Column('mobile_country_code', sa.String(length=128), server_default='', nullable=False))
    op.add_column('invest_users', sa.Column('register_ip', sa.String(length=128), server_default='', nullable=False))
    op.add_column('invest_users', sa.Column('transaction_passwd_salt', sa.String(length=128), server_default='', nullable=False))
    op.add_column('invest_users', sa.Column('transaction_password', sa.String(length=128), server_default='', nullable=False))
    op.create_unique_constraint(None, 'invest_users', ['email'])
    op.add_column('key_salt', sa.Column('source', mysql.TINYINT(display_width=4), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_salt', 'source')
    op.drop_constraint(None, 'invest_users', type_='unique')
    op.drop_column('invest_users', 'transaction_password')
    op.drop_column('invest_users', 'transaction_passwd_salt')
    op.drop_column('invest_users', 'register_ip')
    op.drop_column('invest_users', 'mobile_country_code')
    op.drop_column('invest_users', 'email')
    # ### end Alembic commands ###
