"""alter adminusermodel

Revision ID: 7bb3a33c9e63
Revises: eef9cddaeb12
Create Date: 2018-09-03 17:57:57.930303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb3a33c9e63'
down_revision = 'eef9cddaeb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('password', sa.String(length=128), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'password')
    # ### end Alembic commands ###
