"""alter keysaltmodel

Revision ID: 882351d79124
Revises: 222bf40769c8
Create Date: 2018-10-19 13:50:58.129471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '882351d79124'
down_revision = '222bf40769c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_salt', sa.Column('user_level', mysql.TINYINT(display_width=1), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_salt', 'user_level')
    # ### end Alembic commands ###
