"""alter invest_users

Revision ID: 8ca29cde732e
Revises: e5768c2eeaff
Create Date: 2018-08-31 11:15:18.160035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca29cde732e'
down_revision = 'e5768c2eeaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invest_users', sa.Column('option1', sa.String(length=128), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invest_users', 'option1')
    # ### end Alembic commands ###
