"""alter user

Revision ID: 8cd46a9ee8df
Revises: 089c3fe7c99c
Create Date: 2018-11-09 13:34:09.912644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cd46a9ee8df'
down_revision = '089c3fe7c99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invest_users', sa.Column('user_name', mysql.CHAR(length=64), nullable=True))
    op.create_unique_constraint(None, 'invest_users', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invest_users', type_='unique')
    op.drop_column('invest_users', 'user_name')
    # ### end Alembic commands ###
