"""alter keysalt

Revision ID: 94080f73ab83
Revises: da041d648864
Create Date: 2018-12-11 11:11:55.483095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94080f73ab83'
down_revision = 'da041d648864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
