"""alter adminusermodel

Revision ID: 94401f66dc44
Revises: 5ebdebfa2a5e
Create Date: 2018-09-03 14:34:27.255351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94401f66dc44'
down_revision = '5ebdebfa2a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('bcrypt_salt', sa.String(length=128), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'bcrypt_salt')
    # ### end Alembic commands ###
