"""alter sms message

Revision ID: b8c337fb037d
Revises: ba1f7801980a
Create Date: 2018-12-13 10:38:06.168912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8c337fb037d'
down_revision = 'ba1f7801980a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('send_message', sa.String(length=1024), server_default='', nullable=False),
    sa.Column('response_message', sa.String(length=1024), server_default='', nullable=False),
    sa.Column('gateway', sa.String(length=16), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('aws_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_message',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('update_at', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('send_message', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=False),
    sa.Column('response_message', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('sms_message')
    # ### end Alembic commands ###
