"""alter adminusermodel

Revision ID: badd50650295
Revises: 478616c516d1
Create Date: 2018-09-03 17:14:01.839117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badd50650295'
down_revision = '478616c516d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('admin_users', sa.Column('name', sa.String(length=64), server_default='', nullable=False))
    op.add_column('admin_users', sa.Column('password', sa.String(length=64), server_default='', nullable=False))
    op.add_column('admin_users', sa.Column('platform', sa.String(length=64), server_default='', nullable=False))
    op.create_unique_constraint(None, 'admin_users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='unique')
    op.drop_column('admin_users', 'platform')
    op.drop_column('admin_users', 'password')
    op.drop_column('admin_users', 'name')
    op.drop_column('admin_users', 'level')
    # ### end Alembic commands ###
