"""alter keysalt

Revision ID: bc1cf5e73385
Revises: 4a5726981920
Create Date: 2018-10-19 14:19:32.295404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc1cf5e73385'
down_revision = '4a5726981920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_salt', sa.Column('user_level', mysql.TINYINT(display_width=1), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_salt', 'user_level')
    # ### end Alembic commands ###
