"""add keysaltmodel

Revision ID: ca8f4e92d51b
Revises: a86578bd13a1
Create Date: 2018-09-03 09:03:49.844001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca8f4e92d51b'
down_revision = 'a86578bd13a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_salt',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('user_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('user_type', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('request_type', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('bcrypt_salt', sa.String(length=128), server_default='', nullable=False),
    sa.Column('server_public_key', sa.TEXT(length=1280), nullable=False),
    sa.Column('server_private_key', sa.TEXT(length=1280), nullable=False),
    sa.Column('share_key', sa.String(length=256), server_default='', nullable=False),
    sa.Column('client_public_key', sa.TEXT(length=1280), nullable=False),
    sa.Column('nonce', sa.String(length=128), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_salt')
    # ### end Alembic commands ###
