"""alter user

Revision ID: e0d8caf7f33f
Revises: 60d02e031b3e
Create Date: 2018-11-09 09:54:34.353370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0d8caf7f33f'
down_revision = '60d02e031b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('real_name', table_name='invest_users')
    op.drop_column('invest_users', 'real_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invest_users', sa.Column('real_name', mysql.VARCHAR(length=64), server_default=sa.text("''"), nullable=True))
    op.create_index('real_name', 'invest_users', ['real_name'], unique=True)
    # ### end Alembic commands ###
