"""add invest_users

Revision ID: e5768c2eeaff
Revises: 
Create Date: 2018-08-31 10:05:07.731133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5768c2eeaff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invest_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('user_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('user_mobile', mysql.CHAR(length=12), server_default='', nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('password', sa.String(length=128), server_default='', nullable=False),
    sa.Column('passwd_salt', sa.String(length=128), server_default='', nullable=False),
    sa.Column('bcrypt_salt', sa.String(length=128), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invest_users')
    # ### end Alembic commands ###
