"""alter adminusermodel

Revision ID: eef9cddaeb12
Revises: 097992af7dc6
Create Date: 2018-09-03 17:57:45.358820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eef9cddaeb12'
down_revision = '097992af7dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('password', mysql.VARCHAR(length=64), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###
