"""alter apitokenservice

Revision ID: ff76479864bf
Revises: 4c87f1d66651
Create Date: 2018-10-31 14:04:51.552266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff76479864bf'
down_revision = '4c87f1d66651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_token', sa.Column('source', mysql.TINYINT(display_width=4), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_token', 'source')
    # ### end Alembic commands ###
