"""create TokenNodeConfModel

Revision ID: d7175d3ef3ba
Revises: ba1ff322b21f
Create Date: 2018-12-21 20:08:08.151356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7175d3ef3ba'
down_revision = 'ba1ff322b21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_sign',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('order_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('parameter', sa.String(length=512), server_default='', nullable=False),
    sa.Column('sign', sa.TEXT(), nullable=True),
    sa.Column('response', sa.TEXT(), nullable=True),
    sa.Column('do_result', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('token_node_conf',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('node_env', sa.String(length=16), server_default='dev', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('node_url', sa.String(length=512), server_default='', nullable=False),
    sa.Column('node_port', sa.String(length=16), server_default='', nullable=False),
    sa.Column('server_status', sa.String(length=16), server_default='0', nullable=False),
    sa.Column('script_status', sa.String(length=16), server_default='0', nullable=False),
    sa.Column('mark', sa.String(length=512), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.alter_column('record_pk', 'address',
               existing_type=mysql.MEDIUMTEXT(collation='utf8_bin'),
               nullable=True)
    op.alter_column('record_pk', 'response',
               existing_type=mysql.MEDIUMTEXT(collation='utf8_bin'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record_pk', 'response',
               existing_type=mysql.MEDIUMTEXT(collation='utf8_bin'),
               nullable=False)
    op.alter_column('record_pk', 'address',
               existing_type=mysql.MEDIUMTEXT(collation='utf8_bin'),
               nullable=False)
    op.drop_table('token_node_conf')
    op.drop_table('record_sign')
    # ### end Alembic commands ###
