"""db init

Revision ID: ba1ff322b21f
Revises: 
Create Date: 2018-12-12 16:10:17.431305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba1ff322b21f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_pk',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('order_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.Column('category', sa.String(length=128), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('secret_btc',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sub_index', sa.BigInteger(), nullable=False),
    sa.Column('change_index', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_private_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_public_address', sa.String(length=255), server_default='', nullable=False),
    sa.Column('acct_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sub_private_key_aes'),
    sa.UniqueConstraint('sub_public_address'),
    sa.UniqueConstraint('sub_public_key_aes')
    )
    op.create_table('secret_btc_gather',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sub_index', sa.BigInteger(), nullable=False),
    sa.Column('change_index', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_private_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_public_address', sa.String(length=255), server_default='', nullable=False),
    sa.Column('acct_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sub_private_key_aes'),
    sa.UniqueConstraint('sub_public_address'),
    sa.UniqueConstraint('sub_public_key_aes')
    )
    op.create_table('secret_eth',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sub_index', sa.BigInteger(), nullable=False),
    sa.Column('change_index', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_private_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_public_address', sa.String(length=255), server_default='', nullable=False),
    sa.Column('acct_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sub_private_key_aes'),
    sa.UniqueConstraint('sub_public_address'),
    sa.UniqueConstraint('sub_public_key_aes')
    )
    op.create_table('secret_eth_gather',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sub_index', sa.BigInteger(), nullable=False),
    sa.Column('change_index', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_private_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('sub_public_address', sa.String(length=255), server_default='', nullable=False),
    sa.Column('acct_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sub_private_key_aes'),
    sa.UniqueConstraint('sub_public_address'),
    sa.UniqueConstraint('sub_public_key_aes')
    )
    op.create_table('token_coin',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('coin_name', sa.String(length=128), server_default='', nullable=False),
    sa.Column('coin_des', sa.String(length=128), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('coin_id')
    )
    op.create_table('token_salt',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('nonce_aes', sa.String(length=255), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('public_key_aes')
    )
    op.create_table('wallet_btc',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sub_index', sa.BigInteger(), nullable=False),
    sa.Column('sub_public_address', sa.String(length=255), server_default='', nullable=False),
    sa.Column('change_index', sa.String(length=255), server_default='', nullable=False),
    sa.Column('acct_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('account_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('amount', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('amount_change', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('amount_frozen', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sub_public_address')
    )
    op.create_table('wallet_btc_gather',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sub_index', sa.BigInteger(), nullable=False),
    sa.Column('sub_public_address', sa.String(length=255), server_default='', nullable=False),
    sa.Column('change_index', sa.String(length=255), server_default='', nullable=False),
    sa.Column('acct_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('account_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('amount', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('amount_change', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('amount_frozen', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('desc', sa.String(length=255), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sub_public_address')
    )
    op.create_table('wallet_eth',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sub_index', sa.BigInteger(), nullable=False),
    sa.Column('sub_public_address', sa.String(length=255), server_default='', nullable=False),
    sa.Column('change_index', sa.String(length=255), server_default='', nullable=False),
    sa.Column('acct_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('account_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('amount', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('amount_change', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('amount_frozen', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sub_public_address')
    )
    op.create_table('wallet_eth_gather',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sub_index', sa.BigInteger(), nullable=False),
    sa.Column('sub_public_address', sa.String(length=255), server_default='', nullable=False),
    sa.Column('change_index', sa.String(length=255), server_default='', nullable=False),
    sa.Column('acct_public_key_aes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('coin_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('account_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('amount', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('amount_change', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('amount_frozen', sa.Numeric(precision=21, scale=18), server_default='0.000000000000000000', nullable=False),
    sa.Column('desc', sa.String(length=255), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sub_public_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_eth_gather')
    op.drop_table('wallet_eth')
    op.drop_table('wallet_btc_gather')
    op.drop_table('wallet_btc')
    op.drop_table('token_salt')
    op.drop_table('token_coin')
    op.drop_table('secret_eth_gather')
    op.drop_table('secret_eth')
    op.drop_table('secret_btc_gather')
    op.drop_table('secret_btc')
    op.drop_table('record_pk')
    # ### end Alembic commands ###
